/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codekong_com_jnitest_MainActivity */

#ifndef _Included_codekong_com_jnitest_MainActivity
#define _Included_codekong_com_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codekong_com_jnitest_MainActivity
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codekong_com_jnitest_MainActivity_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
